# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Suburb.create(name: "Aro Valley")
Suburb.create(name: "Berhampore")
Suburb.create(name: "Breaker Bay")
Suburb.create(name: "Brooklyn")
Suburb.create(name: "Churton Park")
Suburb.create(name: "Crofton Downs")
Suburb.create(name: "Glenside")
Suburb.create(name: "Grenada North")
Suburb.create(name: "Happy Valley")
Suburb.create(name: "Hataitai")
Suburb.create(name: "Horokiwi")
Suburb.create(name: "Houghton Bay")
Suburb.create(name: "Island Bay")
Suburb.create(name: "Johnsonville")
Suburb.create(name: "Kaiwharawhara")
Suburb.create(name: "Kelburn")
Suburb.create(name: "Khandallah")
Suburb.create(name: "Kilbirnie")
Suburb.create(name: "Linden")
Suburb.create(name: "Lyall Bay")
Suburb.create(name: "Makara")
Suburb.create(name: "Miramar")
Suburb.create(name: "Mornington")
Suburb.create(name: "Mount Cook")
Suburb.create(name: "Mount Victoria")
Suburb.create(name:"Newlands")
Suburb.create(name: "Ngaio")
Suburb.create(name: "Ngauranga")
Suburb.create(name: "Ohariu")
Suburb.create(name: "Oriental Bay")
Suburb.create(name: "Owhiro Bay")
Suburb.create(name: "Paparangi")
Suburb.create(name: "Redwood")
Suburb.create(name: "Rongotai")
Suburb.create(name: "Roseneath")
Suburb.create(name: "Seatoun")
Suburb.create(name: "Shelly Bay")
Suburb.create(name: "Strathmore Park")
Suburb.create(name: "Tawa")
Suburb.create(name: "Te Aro")
Suburb.create(name: "Vogeltown")
Suburb.create(name: "Wadestown")
Suburb.create(name: "Wellington Central")
Suburb.create(name: "Wilton")
Suburb.create(name: "Worser Bay")

